### ISSUE TITLE
is there any way of making the full image appear when the image posted on the instagram isn't square?

### ISSUE THREAD

**Issue by EltonMcJosh** [fernandod1/Instagram-to-discord#5]

**Comment by fernandod1** [comment]
Please uncomment line 78 of code:

#embed["image"] = {"url":get_last_thumb_url(html)} # unmark to post bigger image

Test script and tell me if new image size is the one you require.

**Comment by InvisibleOS** [comment]
> Please uncomment line 78 of code:
> 
> #embed["image"] = {"url":get_last_thumb_url(html)} # unmark to post bigger image
> 
> Test script and tell me if new image size is the one you require.

Even this just makes it a square. It takes the thumbnail of the post on Instagram I guess. It doesn't take the whole image that was posted. There are some posts that are of different dimensions. This posts a bigger image but it's just a square. 
I think a way to get the post from the post link should be added so that the complete image is posted instead of just a square. The square image sometimes cuts a part of the post.

Edit: I figured it out. To get the full-sized photo for the larger image you simply need to type 
```py
embed["image"] = {"url":get_last_image_url(html)}
```
instead of `embed["image"] = {"url":get_last_thumb_url(html)}`

**Comment by fernandod1** [comment]
Thanks for sharing discovery
